---
- name: configure elastic repo
  include_role:
    name: nephelaiio.elastic_repo
  when: metricbeat_repo_manage | bool

- name: inspect packages
  package_facts:
    manager: auto

- block:

    - block:

        - name: install yum version lock support
          package:
            name: yum-plugin-versionlock

        - name: disable yum package lock
          community.general.yum_versionlock:
            name: "{{ item }}"
            state: absent
          loop: "{{ [metricbeat_package_names] | flatten }}"
          when: item in packages
          tags:
            - skip_ansible_lint

      when: (ansible_os_family | lower) == 'redhat'

    - name: disable apt package lock
      dpkg_selections:
        name: "{{ item }}"
        selection: install
      loop: "{{ [metricbeat_package_names] | flatten }}"
      when:
        - (ansible_os_family | lower) == 'debian'
        - item in packages

  when: metricbeat_package_hold | bool

- name: install metricbeat packages
  package:
    name: "{{ metricbeat_package_names }}"
    state: "{{ metricbeat_package_state }}"

- block:

    - block:

        - name: enable apt package hold
          dpkg_selections:
            name: "{{ item }}"
            selection: hold
          loop: "{{ [metricbeat_package_names] | flatten }}"
          when: (ansible_os_family | lower) == 'debian'

        - name: enable yum package lock
          community.general.yum_versionlock:
            name: "{{ item }}"
            state: present
          loop: "{{ [metricbeat_package_names] | flatten }}"
          when: (ansible_os_family | lower) == 'redhat'
          tags:
            - skip_ansible_lint

      when: metricbeat_package_hold | bool

    - name: manage metricbeat main configuration file
      copy:
        content: |
          # Ansible managed

          {{ metricbeat_conf | to_nice_yaml(indent=2) }}
        dest: "{{ metricbeat_conf_path }}"
      notify: restart metricbeat

    - name: prune stale metricbeat module configuration files
      file:
        path: "{{ metricbeat_conf_modules_path }}/{{ module_name }}.yml.disabled"
        state: absent
      loop_control:
        loop_var: module_name
        label: "{{ module_name }}"
      loop: "{{ metricbeat_conf_modules | map(attribute='module') | list | unique }}"

    - name: manage metricbeat module configuration files
      copy:
        dest: "{{ metricbeat_conf_modules_path }}/{{ module_name }}.yml"
        content: |
          ---
          {{ module_conf | to_nice_yaml(indent=2) }}
        mode: 0640
      vars:
        module_conf: "{{ metricbeat_conf_modules | selectattr('module', 'equalto', module_name) | list }}"
      loop_control:
        loop_var: module_name
        label: "{{ module_name }}"
      notify: restart metricbeat
      loop: "{{ metricbeat_conf_modules | map(attribute='module') | list | unique }}"
      when: metricbeat_conf_manage | bool

    - name: manage metricbeat services
      service:
        name: "{{ metricbeat_service_name }}"
        state: "{{ metricbeat_service_status }}"
        enabled: "{{ metricbeat_service_enabled }}"

  when: metricbeat_package_state in ['present', 'latest']
